spring:
  application:
    name: spring-cloud-eureka-client
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true